name: flutter_maps
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter_web: ^0.5.4
  google_maps_flutter: ^2.4.0
  intl: ^0.18.1
  webview_flutter: ^4.2.3
  provider: ^6.0.5
  shrine_images: ^2.0.2
  path_provider: ^2.1.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
      - assets/locations.json
      - packages/shrine_images/0-0.jpg
      - packages/shrine_images/1-0.jpg
      - packages/shrine_images/2-0.jpg
      - packages/shrine_images/3-0.jpg
      - packages/shrine_images/4-0.jpg
      - packages/shrine_images/5-0.jpg
      - packages/shrine_images/6-0.jpg
      - packages/shrine_images/7-0.jpg
      - packages/shrine_images/8-0.jpg
      - packages/shrine_images/9-0.jpg
      - packages/shrine_images/10-0.jpg
      - packages/shrine_images/11-0.jpg
      - packages/shrine_images/12-0.jpg
      - packages/shrine_images/13-0.jpg
      - packages/shrine_images/14-0.jpg
      - packages/shrine_images/15-0.jpg
      - packages/shrine_images/16-0.jpg
      - packages/shrine_images/17-0.jpg
      - packages/shrine_images/18-0.jpg
      - packages/shrine_images/19-0.jpg
      - packages/shrine_images/20-0.jpg
      - packages/shrine_images/21-0.jpg
      - packages/shrine_images/22-0.jpg
      - packages/shrine_images/23-0.jpg
      - packages/shrine_images/24-0.jpg
      - packages/shrine_images/25-0.jpg
      - packages/shrine_images/26-0.jpg
      - packages/shrine_images/27-0.jpg
      - packages/shrine_images/28-0.jpg
      - packages/shrine_images/29-0.jpg
      - packages/shrine_images/30-0.jpg
      - packages/shrine_images/31-0.jpg
      - packages/shrine_images/32-0.jpg
      - packages/shrine_images/33-0.jpg
      - packages/shrine_images/34-0.jpg
      - packages/shrine_images/35-0.jpg
      - packages/shrine_images/36-0.jpg
      - packages/shrine_images/37-0.jpg